// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var WithUseEffect$ReactHooksTemplate = require("./WithUseEffect.bs.js");
var WithUseEffect0$ReactHooksTemplate = require("./WithUseEffect0.bs.js");

function App(Props) {
  return React.createElement("div", undefined, React.createElement(WithUseEffect$ReactHooksTemplate.make, { }), React.createElement(WithUseEffect0$ReactHooksTemplate.make, { }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
