// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Timer$ReactHooksTemplate = require("./Timer.bs.js");
var DocsTick$ReactHooksTemplate = require("./DocsTick.bs.js");
var TimerHooks$ReactHooksTemplate = require("./TimerHooks.bs.js");

function App(Props) {
  return React.createElement("div", undefined, React.createElement(Timer$ReactHooksTemplate.make, { }), React.createElement(TimerHooks$ReactHooksTemplate.make, { }), React.createElement(DocsTick$ReactHooksTemplate.make, { }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
