// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function DocsTick(Props) {
  var match = React.useState((function () {
          return {
                  count: 0
                };
        }));
  var dispatch = match[1];
  var state = match[0];
  React.useEffect((function () {
          var timerId = setInterval((function (param) {
                  return Curry._1(dispatch, (function (param) {
                                return {
                                        count: state.count + 1 | 0
                                      };
                              }));
                }), 1000);
          return (function (param) {
                    clearInterval(timerId);
                    return /* () */0;
                  });
        }));
  return React.createElement("div", undefined, String(state.count));
}

var make = DocsTick;

exports.make = make;
/* react Not a pure module */
